@PremiumCalculator.API_HostAddress = http://localhost:5222/api

POST {{PremiumCalculator.API_HostAddress}}/PremiumCalculator/CalculatePremium
Accept: application/json
content-type: application/json
{
     "Name": "John Doe",    
     "DateOfBirth": "1990-01-11",
     "AgeNextBirthDay": "35",
     "OccupationId": "1", 
     "Occupation": "Doctor",
     "SumInsured": "50000"
}

###
