// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PremiumCalculator.Domain.Entities;

namespace PremiumCalculator.Infrastructure.Persistance;

public partial class PremiumCalculatorDbContext : DbContext
{
    public PremiumCalculatorDbContext(DbContextOptions<PremiumCalculatorDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<Occupation> Occupations { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<VOccupationRating> VOccupationRatings { get; set; }

    public virtual DbSet<VOccupationRatingFactor> VOccupationRatingFactors { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Member__3214EC0712FD507F");

            entity.ToTable("Member");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SumInsured).HasColumnType("money");

            entity.HasOne(d => d.Occupation).WithMany(p => p.Members)
                .HasForeignKey(d => d.OccupationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Member__Occupati__3D5E1FD2");
        });

        modelBuilder.Entity<Occupation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Occupati__3214EC0744BBF178");

            entity.ToTable("Occupation");

            entity.Property(e => e.Occupation1)
                .IsRequired()
                .HasMaxLength(25)
                .HasColumnName("Occupation");

            entity.HasOne(d => d.Rating).WithMany(p => p.Occupations)
                .HasForeignKey(d => d.RatingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Occupatio__Ratin__3A81B327");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Rating__3214EC07D47DCC62");

            entity.ToTable("Rating");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Factor).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Rating1)
                .IsRequired()
                .HasMaxLength(15)
                .HasColumnName("Rating");
        });

        modelBuilder.Entity<VOccupationRating>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("V_OccupationRating");

            entity.Property(e => e.Occupation)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.Rating)
                .IsRequired()
                .HasMaxLength(15);
        });

        modelBuilder.Entity<VOccupationRatingFactor>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("V_OccupationRatingFactor");

            entity.Property(e => e.Factor).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Occupation)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.Rating)
                .IsRequired()
                .HasMaxLength(15);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}