// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PremiumCalculator.Domain.Entities;

public partial class Member
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public byte AgeNextBirthDay { get; set; }

    public int OccupationId { get; set; }

    public decimal SumInsured { get; set; }

    public virtual Occupation Occupation { get; set; }
}