// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PremiumCalculator.Domain.Entities;

public partial class Occupation
{
    public int Id { get; set; }

    public string OccupationName { get; set; }

    public int RatingId { get; set; }

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();

    public virtual Rating Rating { get; set; }
}