// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PremiumCalculator.Domain.Entities;

public partial class Rating
{
    public int Id { get; set; }

    public string Rating1 { get; set; }

    public decimal Factor { get; set; }

    public virtual ICollection<Occupation> Occupations { get; set; } = new List<Occupation>();
}