// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PremiumCalculator.Domain.Entities;

public partial class VOccupationRatingFactor
{
    public string Occupation { get; set; }

    public string Rating { get; set; }

    public decimal Factor { get; set; }
}